config/routes.rb
Rails.application.routes.draw do
  
  resources :events
  resources :teams
  
  ## a bit of a workaround route here to patch an already existing account and adding their extending details to it
  as :user do
    put '/user/confirmation' => 'confirmations#update', :via => :patch, :as => :update_user_confirmation
  end
  
  devise_for :users, controllers: {
    registrations: 'registrations',
    confirmations: 'confirmations'
  }
  
  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/event.rb
class Event < ApplicationRecord
    ## adding some relations between the event and the team and user - these can belong to both the team and the user
    belongs_to :team
    belongs_to :user
    
    ##when new event created I do want to assign it to a team
    accepts_nested_attributes_for :team
    
    include PublicActivity::Model
    tracked owner: Proc.new { |controller, model| controller.current_user}
    
    ##for photos added to events - use s3
    ##has_one_attached :event_picture
    ##event_picture.attach(params[:event_picture])
end

app/controllers/events_controller.rb
##logger for logging when new events are creat and writes to log file - uses the singleton design pattern 
require 'my_logger'
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all.order("created_at DESC")
  end
  

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new 
  # new method on a event trying to find the team name (querying db) and pull out. so can display the team
  def new
    @event = current_user.events.build
    @teams = Team.where('id = ?', current_user.team_id)
  end

  # GET /events/1/edit
  # need to find teams to edit - bit of an odd end usecase.
  def edit
    
    @teams = current_user.teams
    
  end

  # POST /events
  # POST /events.json 
  # redirect to event after create it
  def create
    
    @event = current_user.events.build(event_params)
    logger = MyLogger.instance
    logger.logInformation("An event was created")
    
   
    # logger.logInformation(Time.now.strftime('%m/%d/%y %h:%m %p') + @event.name + "An event was created")

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json 
  # redirect to event after edit/update it
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json  add teamid here also to whitelist these and pass them through form so know they are secure. after destroy event, redircect to the root path
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to root_path, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions. save having to put this into every action
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through. rails can psas the below params now through a form
    def event_params
      params.require(:event).permit(:name, :description, :team_id)
    end
    
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= simple_form_for(@event) do |f| %>
  <%= f.error_notification %>

	<%# if a user has a team id need to display a form to create an event, if not, dont want to as a event needs a team id  %>
	
	<% if !current_user.team_id.blank? %>
   <div class="field">
   	<div class="control">
   		<%= f.input :name, input_html: { class: "input" }, wrapper: false, label_html: { class: "label"} %>
   	</div>
   </div>
   <div class="field">
   	<div class="control">
   		<%= f.input :description, input_html: { class: "textarea" }, wrapper: false, label_html: { class: "label"} %>
   	</div>
   </div>
   
   

   <div class="field">
   	<div class="control">
   		<label class="label">Team</label>
   		<div class="control has-icons-left">
   			<span class="select">
   				<%= f.input_field :team_id, collection: @teams, prompt: "Select team" %>
   			</span>
   			<span class="icon is-small is-left">
   				<i class="fa fa-users"></i>
   			</span>
   		</div>
   	</div>
   </div>

   <div class="field">
   	<div class="control">
   		<%= f.button :submit, class: "button is-link" %>
   	</div>
   </div>
	<% else %>
	
		<article class="message is-warning">
			<div class="message-body">
				<strong>It looks as though you are not part of a team yet!</strong>
				<p>You can create a team or get invited by another user to join.</p>
				<br />
				<%= link_to 'Create a team', new_team_path, class:'button' %>
			</div>
		</article>

	<% end %>

<% end %>

app/views/events/edit.html.erb
<div class="section">
	<div class="container">
		<h1 class="title is-2">Editing Event</h1>
		<%= render 'form', event: @event %>
	</div>
</div>

app/views/events/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Events</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= event.name %></td>
        <td><%= event.description %></td>
        <td><%= link_to 'Show', event %></td>
        <td><%= link_to 'Edit', edit_event_path(event) %></td>
        <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Event', new_event_path %>

app/views/events/new.html.erb
<div class="section">
	<div class="container">
		<h1 class="title is-2">New Event</h1>
	
		<%= render 'form', event: @event %>
	<br />
	<%= link_to 'Back', events_path, class:'button' %>
	</div>
</div>

app/views/events/show.html.erb
<section class="section">
  
	<div class="container">
	  
		<div class="columns is-centered">
		  
			<div class="column is-9">
			  
				<h1 class="title is-2"><%= @event.name %></h1>
				
				<h2 class="subtitle is-5 has-text-weight-light"><span class="icon is-small has-text-weight-lighter"><i class="fa fa-users"></i>&nbsp; &nbsp;</span> <%= link_to @event.team.name, team_path(@event.team) %></h2>
			
				<div class="level">
					<div class="level-left">
						<p>Created on
							<%= verbose_date(@event.created_at) %> by <%= @event.user.name %> / Modified
							<%= time_ago_in_words(@event.updated_at) %></p>
					</div>
					<div class="level-right">
						<div class="buttons">
							<%= link_to 'Edit Event', edit_event_path(@event), class:'button' %>
							<%= link_to 'Delete Event', @event, method: :delete, data: { confirm: 'Are you sure'}, class:'button is-danger is-outlined' %> 
						</div>
					</div>
				
				</div>
				<hr />
				
				<div class="content">
					<%= @event.description.html_safe %>
				</div>
			</div>
		</div>
	</div>
</section>